### ISSUE TITLE
Ajouter les output pour statistiques

### ISSUE THREAD

**Issue by nilovna** [GitMyCode/Minesweeper-AI#22]

**Comment by Freddrickk** [comment]
Est-ce que je pourrais avoir la photo du tableau ?

**Comment by GitMyCode** [comment]
![image1](https://cloud.githubusercontent.com/assets/3288428/5196108/983d2744-74f5-11e4-96e8-c7a8d3f001a2.JPG)

**Comment by GitMyCode** [comment]
c'est tout  ce que j'ai

**Comment by Freddrickk** [comment]
Ahahahah je viens de me rendre compte que c'est moi qui a pris la photo haha !

**Comment by Freddrickk** [comment]
J'hésite entre poster la photo parce que tu viens de le faire ou de me dire que c'est justement ce que je ne devrais pas faire parce que ça fait trop Martin-too-much-avec-ses-images

**Comment by Freddrickk** [comment]
- [x] Interface Benchmarkable et implémentation par AI
- [x] Taux de succès des probabilités
- [x] Taux par catégorie (trivial, CSP, probabiliste)
- [x] Temps de résolution
- [x] % victoires / défaites
- [x] Ajout des stats dans Benchmark.java

**Comment by Freddrickk** [comment]
Les temps d'exécution on s'entend pour dire que ces temps sont uniquement calculés en cas de victoire ?

**Comment by GitMyCode** [comment]
oui sinon un AI qui perds tout le temps aura des temps très bas
