### ISSUE TITLE
Foward checking

### ISSUE THREAD

**Issue by GitMyCode** [GitMyCode/Minesweeper-AI#25]
On n'utilise pas l'heuristique du Foward cheking.

Pour l'implanter il faudrait, pour chaque combinaison de flag, désactivé les cases encore disponibles autour de la variable (un boolean dans FringeNode)

**Comment by GitMyCode** [comment]
#24  Si on fait du foward checking on n'a plus besoin de verifier si le dernier placement de flag invalide une variable précédente. La seul vérification qui reste est le check de la variable présente.

**Comment by GitMyCode** [comment]
Ok je viens de le faire et c'est en effet enormément plus rapide

**Comment by GitMyCode** [comment]
![image](https://cloud.githubusercontent.com/assets/3288428/5236065/76fcca48-77ee-11e4-81d0-b6df24b31785.png)

**Comment by Freddrickk** [comment]
Nice ! Et on peut facilement faire un AI qui choisi un ou l'autre ?

**Comment by GitMyCode** [comment]
Nah :/ j'ai rien codé de bien modulaire. Je l'ai juste fait marcher.
Pour les Ai je pensais qu'on devrait pas avoir CSP comme un AI valide. On a des Ai qui _utilise_ CSP pour les probabilités.
Donc dans le fond on présente les différentes versions de CSP qu'on a fait et les temps qui comparent leur vitesse. Mais les AI vont tous utiliser le même CSP qui sera le meilleur.

Fak dans le fond CSP c'est juste une methode static dans une classe qui prend un Graph et effectue ses opérations dessus.

Les Ai qui reste serait donc:
- Random (juste pour rire..)
- Seulement coups certains + random
- Probabilité
- Probabilité + end game

**Comment by GitMyCode** [comment]
Donc 
- Présentation des techniques de CSP
  - Évalué selon leur vitesse
- Présentation des techniques de AI
  - Évalué selon leur taux de victoire

**Comment by GitMyCode** [comment]
Ce soir je vais faire une classe CSP et séparer les différentes stratégies de CSP avec le pattern strategy justement. Mais vos AI vont toujours prendre le CSP le plus rapide.

**Comment by GitMyCode** [comment]
OK oublier ca.
