### ISSUE TITLE
Statistique Minesweeper

### ISSUE THREAD

**Issue by GitMyCode** [GitMyCode/Minesweeper-AI#3]
Je sais pas qui veut faire ca: @nilovna  @louib @Freddrickk 
## B. Problématique 10 %

> - Identification du problème à résoudre.
>   - Type de problème : apprentissage? prise de décision? raisonnement? optimisation? probabiliste?  etc.?
> - Identification des caractérisitiques du problème.
>   - Ex: discret ou cotinue? partiellement ou totalement observable? déterministe ou non déterministe? Etc.
> - La problématique offre-t-elle un challenge? Nécessite-t-elle vraiment de l'IA? Une approche naïve peut-elle résoudre facilement le problème?
> - Le niveau de difficulté peut être considéré.

**Comment by nikixiaoyou** [comment]
C'est bon j'avais l'intention de le faire!

**Comment by nikixiaoyou** [comment]
Je vais créer des issues en lien avec la remise au lieu qu'elles soient en lien avec l'évaluation.
