### ISSUE TITLE
Erreur dans les limites de la grid

### ISSUE THREAD

**Issue by GitMyCode** [GitMyCode/Minesweeper-AI#9]
isStepInThisDirInGrid n'existe plus et cela cause un bug. A cause de mon choix d'utiliser une grille 1 dimension il faut faire attention au moment d'aller dans une direction si on est belle et bien sur la meme ligne.

![bug](https://cloud.githubusercontent.com/assets/3288428/5173691/c1ba7200-73f8-11e4-9efc-7b9309e1b77f.png)

**Comment by louib** [comment]
C'est un peu de ça que je parlais quand je disais que c'était moins lisible à une dimension. On aurait pas ce problème avec 2 dimensions, qui est la représentation naturelle dans le cas d'une grille de démineur. Je vais faire un revert sur mon commit.

**Comment by GitMyCode** [comment]
Oui c'est vrai. On peut argumenter de mettre ça en 2d
